// AUTO-GENERATED by site/scripts/capture-real-data.mjs — do not edit by hand.
// Dogfooded from the real `cv` index of this monorepo. Regenerate with:
//   node site/scripts/capture-real-data.mjs
// Captured: 2026-07-20T17:20:37.461Z

export const repoStats = {
  "files": 109,
  "symbols": 452,
  "edges": 767,
  "chunks": 746,
  "dbSize": "11.0 MB",
  "indexed": "2026-07-18 18:49:32",
  "health": {
    "ok": 81,
    "degraded": 28,
    "failed": 0,
    "skipped": 0
  },
  "languages": [
    {
      "name": "typescript",
      "count": 80
    },
    {
      "name": "unknown",
      "count": 28
    },
    {
      "name": "javascript",
      "count": 1
    }
  ],
  "topFiles": [
    {
      "path": "_research/batch1_deepdive.md",
      "tokens": 15377
    },
    {
      "path": "_research/batch3_deepdive.md",
      "tokens": 12715
    },
    {
      "path": "packages/core/src/Engine.ts",
      "tokens": 10644
    },
    {
      "path": "_research/batch2_deepdive.md",
      "tokens": 9511
    },
    {
      "path": "packages/dashboard/web/app.js",
      "tokens": 9088
    },
    {
      "path": "_research/plans/v2.md",
      "tokens": 8936
    }
  ]
} as const;

export const rawTotal = {
  "tokens": 194420,
  "files": 139
} as const;

export const packStops = [
  {
    "budget": 10000,
    "actualTokens": 10000,
    "files": 17,
    "expandable": 108,
    "layers": {
      "outline": 5,
      "skeleton": 7,
      "full": 5
    }
  },
  {
    "budget": 32000,
    "actualTokens": 31999,
    "files": 15,
    "expandable": 31,
    "layers": {
      "full": 11,
      "skeleton": 3,
      "outline": 1
    }
  },
  {
    "budget": 128000,
    "actualTokens": 128000,
    "files": 65,
    "expandable": 7,
    "layers": {
      "full": 62,
      "outline": 1,
      "skeleton": 2
    }
  }
] as const;

export const packSample = [
  {
    "path": "packages/core/src/Engine.ts",
    "layer": "full",
    "tokens": 10689
  },
  {
    "path": "packages/dashboard/web/app.js",
    "layer": "full",
    "tokens": 9073
  },
  {
    "path": "packages/core/src/indexdb/rank.ts",
    "layer": "full",
    "tokens": 2504
  },
  {
    "path": "packages/core/src/indexdb/db.ts",
    "layer": "full",
    "tokens": 2010
  },
  {
    "path": "packages/core/src/assemble/compress/layer.test.ts",
    "layer": "full",
    "tokens": 1807
  },
  {
    "path": "packages/cli/src/commands/status.ts",
    "layer": "full",
    "tokens": 1315
  }
] as const;

export const packLayerExamples = {
  "full": [
    {
      "path": "packages/core/src/assemble/compress/layer.test.ts",
      "layer": "full"
    },
    {
      "path": "packages/core/src/assemble/expand-store.ts",
      "layer": "full"
    }
  ],
  "compressed": [
    {
      "path": "packages/cli/src/commands/status.ts",
      "layer": "skeleton"
    },
    {
      "path": "packages/core/src/Engine.ts",
      "layer": "skeleton"
    }
  ]
} as const;

export const fidelityExample = {
  "path": "packages/cli/src/commands/status.ts",
  "fullTokens": 1315,
  "compressedTokens": 169,
  "layer": "skeleton"
} as const;

export const fullExample = {
  "path": "packages/core/src/indexdb/rank.ts",
  "tokens": 2504
} as const;

export const searches = [
  {
    "query": "pack",
    "total": 4,
    "hits": [
      {
        "file": "core/src/Engine.ts",
        "startLine": 348,
        "endLine": 362,
        "bm25": 3.23,
        "graph": 17,
        "rrf": 0.0286,
        "related": 5
      },
      {
        "file": "dashboard/web/app.js",
        "startLine": 662,
        "endLine": 679,
        "bm25": 3.31,
        "graph": 53,
        "rrf": 0.0252,
        "related": 5
      },
      {
        "file": "dashboard/web/app.js",
        "startLine": 618,
        "endLine": 630,
        "bm25": 3.24,
        "graph": 48,
        "rrf": 0.0251,
        "related": 5
      },
      {
        "file": "dashboard/web/app.js",
        "startLine": 571,
        "endLine": 581,
        "bm25": 3.28,
        "graph": 68,
        "rrf": 0.0239,
        "related": 5
      }
    ]
  },
  {
    "query": "index",
    "total": 4,
    "hits": [
      {
        "file": "core/src/Engine.ts",
        "startLine": 154,
        "endLine": 170,
        "bm25": 2.2,
        "graph": 6,
        "rrf": 0.0301,
        "related": 5
      },
      {
        "file": "core/src/Engine.ts",
        "startLine": 171,
        "endLine": 183,
        "bm25": 2.14,
        "graph": 9,
        "rrf": 0.0286,
        "related": 5
      },
      {
        "file": "core/src/Engine.ts",
        "startLine": 967,
        "endLine": 974,
        "bm25": 2.24,
        "graph": 29,
        "rrf": 0.0269,
        "related": 5
      },
      {
        "file": "core/src/Engine.ts",
        "startLine": 126,
        "endLine": 137,
        "bm25": 2.15,
        "graph": 22,
        "rrf": 0.0267,
        "related": 5
      }
    ]
  },
  {
    "query": "parser",
    "total": 4,
    "hits": [
      {
        "file": "core/src/parse/parser.ts",
        "startLine": 62,
        "endLine": 100,
        "bm25": 6.88,
        "graph": 15,
        "rrf": 0.0297,
        "related": 5
      },
      {
        "file": "core/src/parse/parser.ts",
        "startLine": 1,
        "endLine": 54,
        "bm25": 5.81,
        "graph": 19,
        "rrf": 0.0283,
        "related": 5
      },
      {
        "file": "core/src/parse/index.ts",
        "startLine": 1,
        "endLine": 134,
        "bm25": 5.47,
        "graph": 28,
        "rrf": 0.0265,
        "related": 5
      },
      {
        "file": "core/src/budget/cache.ts",
        "startLine": 52,
        "endLine": 68,
        "bm25": 0,
        "graph": 1,
        "rrf": 0.0164,
        "related": 5
      }
    ]
  }
] as const;

export const callGraph = {
  "root": {
    "name": "Engine::pack",
    "file": "core/src/Engine.ts"
  },
  "callees": [
    {
      "file": "core/src/cache/incremental.ts",
      "startLine": 38,
      "kind": "class",
      "name": "ParseCache",
      "pagerank": 0.0013
    },
    {
      "file": "core/src/assemble/expand-store.ts",
      "startLine": 54,
      "kind": "method",
      "name": "ExpandMapStore::save",
      "pagerank": 0.0028
    },
    {
      "file": "core/src/assemble/compress/index.ts",
      "startLine": 76,
      "kind": "function",
      "name": "compress",
      "pagerank": 0.0011
    },
    {
      "file": "core/src/assemble/expand-store.ts",
      "startLine": 80,
      "kind": "method",
      "name": "ExpandMapStore::load",
      "pagerank": 0.0073
    },
    {
      "file": "core/src/parse/index.ts",
      "startLine": 105,
      "kind": "function",
      "name": "parseFilesCached",
      "pagerank": 0.0013
    }
  ],
  "callers": [
    {
      "file": "dashboard/src/server.ts",
      "startLine": 108,
      "kind": "function",
      "name": "createHandler",
      "pagerank": 0.0016
    }
  ]
} as const;

export const impact = {
  "seed": {
    "name": "compress",
    "file": "core/src/assemble/compress/index.ts"
  },
  "r1Count": 50,
  "r2Count": 15,
  "r1Sample": [
    {
      "name": "registerIndex",
      "file": "cli/src/commands/index.ts"
    },
    {
      "name": "registerSearch",
      "file": "cli/src/commands/search.ts"
    }
  ]
} as const;

export const terminal = {
  "index": "[cv] scanning codingverse\n[cv] built SQLite index at .codingverse/index.db\n  files:   109\n  symbols: 452\n  edges:   767\n  chunks:  746\n  langs:   typescript (80), unknown (28), javascript (1)",
  "rank": "[cv] PageRank over 767 resolved call edges\n[cv] top 5 symbols by rank:\n  1. cache.ts · get  [0.1755]\n  2. cache.ts · set  [0.0945]\n  3. Engine.ts · ingest  [0.0363]\n  4. Engine.ts · close  [0.0192]\n  5. layer.test.ts · find  [0.0162]",
  "pack": "[cv] budget 32,000 tokens\n  [f] core/src/Engine.ts  10,689 tok\n  [f] dashboard/web/app.js  9,073 tok\n  [f] core/src/indexdb/rank.ts  2,504 tok\n  [f] core/src/indexdb/db.ts  2,010 tok\n[cv] raw repo: 194,420 tok\n[cv] packed:   31,999 tok (83.5% saved)",
  "search": "[cv] query \"pack\" · BM25 + call graph, fused via RRF\n  core/src/Engine.ts:348  rrf=0.0286 bm25=3.23 graph=17\n  dashboard/web/app.js:662  rrf=0.0252 bm25=3.31 graph=53\n  dashboard/web/app.js:618  rrf=0.0251 bm25=3.24 graph=48\n  dashboard/web/app.js:571  rrf=0.0239 bm25=3.28 graph=68\n[cv] 4 hits, each carrying call-graph neighbors",
  "serve": "[cv] dashboard on http://127.0.0.1:7331\n[cv] index: .codingverse/index.db (11.0 MB)\n[cv] six boards: overview · token map · code graph\n                 retrieval · pack preview · sync"
} as const;

export const astQueries = {
  "TypeScript": "; Classes\n(class_declaration\n  name: (type_identifier) @name) @definition.class\n\n; Interfaces\n(interface_declaration\n  name: (type_identifier) @name) @definition.interface\n\n; Type aliases\n(type_alias_declaration\n  name: (type_identifier) @name) @definition.type\n\n; Enums\n(enum_declaration\n  name: (identifier) @name) @definition.enum\n\n; Function declarations\n(function_declaration\n  name: (identifier) @name) @definition.function\n\n; Methods\n(method_definition\n  name: (property_identifier) @name) @definition.method\n\n; Arrow / function-expression assigned to a const/let\n(variable_declarator\n  name: (identifier) @name\n  value: [(arrow_function) (function_expression)]) @definition.function\n\n; Call expressions -> reference\n(call_expression\n  function: [\n    (identifier) @name\n    (member_expression property: (property_identifier) @name)\n  ]) @reference.call\n\n; new Foo() -> reference\n(new_expression\n  constructor: [\n    (identifier) @name\n    (member_expression property: (property_identifier) @name)\n  ]) @reference.call",
  "JavaScript": "; Classes\n(class_declaration\n  name: (identifier) @name) @definition.class\n\n; Function declarations\n(function_declaration\n  name: (identifier) @name) @definition.function\n\n; Methods\n(method_definition\n  name: (property_identifier) @name) @definition.method\n\n; Arrow / function-expression assigned to a const/let\n(variable_declarator\n  name: (identifier) @name\n  value: [(arrow_function) (function_expression)]) @definition.function\n\n; Call expressions -> reference\n(call_expression\n  function: [\n    (identifier) @name\n    (member_expression property: (property_identifier) @name)\n  ]) @reference.call\n\n; new Foo() -> reference\n(new_expression\n  constructor: [\n    (identifier) @name\n    (member_expression property: (property_identifier) @name)\n  ]) @reference.call",
  "Python": "; Classes\n(class_definition\n  name: (identifier) @name) @definition.class\n\n; Functions / methods (method vs function disambiguated by enclosing scope later)\n(function_definition\n  name: (identifier) @name) @definition.function\n\n; Calls -> reference\n(call\n  function: [\n    (identifier) @name\n    (attribute attribute: (identifier) @name)\n  ]) @reference.call",
  "Go": "; Functions\n(function_declaration\n  name: (identifier) @name) @definition.function\n\n; Methods (receiver-bound)\n(method_declaration\n  name: (field_identifier) @name) @definition.method\n\n; Struct types\n(type_declaration\n  (type_spec\n    name: (type_identifier) @name\n    type: (struct_type))) @definition.struct\n\n; Interface types\n(type_declaration\n  (type_spec\n    name: (type_identifier) @name\n    type: (interface_type))) @definition.interface\n\n; Other named types (aliases / defined types)\n(type_declaration\n  (type_spec\n    name: (type_identifier) @name\n    type: [(qualified_type) (type_identifier) (pointer_type) (map_type) (slice_type)])) @definition.type\n\n; Calls -> reference\n(call_expression\n  function: [\n    (identifier) @name\n    (selector_expression field: (field_identifier) @name)\n  ]) @reference.call",
  "Rust": "; Functions / methods (function_item inside impl is refined to method later)\n(function_item\n  name: (identifier) @name) @definition.function\n\n; Structs\n(struct_item\n  name: (type_identifier) @name) @definition.struct\n\n; Enums\n(enum_item\n  name: (type_identifier) @name) @definition.enum\n\n; Traits -> interface\n(trait_item\n  name: (type_identifier) @name) @definition.interface\n\n; Type aliases\n(type_item\n  name: (type_identifier) @name) @definition.type\n\n; Calls -> reference\n(call_expression\n  function: [\n    (identifier) @name\n    (field_expression field: (field_identifier) @name)\n    (scoped_identifier name: (identifier) @name)\n  ]) @reference.call",
  "Java": "; Classes\n(class_declaration\n  name: (identifier) @name) @definition.class\n\n; Interfaces\n(interface_declaration\n  name: (identifier) @name) @definition.interface\n\n; Enums\n(enum_declaration\n  name: (identifier) @name) @definition.enum\n\n; Methods\n(method_declaration\n  name: (identifier) @name) @definition.method\n\n; Constructors -> method\n(constructor_declaration\n  name: (identifier) @name) @definition.method\n\n; Calls -> reference\n(method_invocation\n  name: (identifier) @name) @reference.call\n\n; Object creation -> reference (new Foo())\n(object_creation_expression\n  type: (type_identifier) @name) @reference.call"
} as const;
